import { renderLayout } from "../shared/layout.mjs";

const body = `
<section class="cie-section cie-hero"><div class="cie-inner"><p class="eyebrow">01 — CIE Professional</p><h1>Your career is bigger than your résumé.</h1><p class="opening">Most professional tools start with a résumé, job title, or list of skills.<strong>CIE starts with your curiosity.</strong></p><div class="quiet-paths"><a href="#understanding">See how understanding grows</a><a href="#beyond">What is CIE?</a></div><div class="hero-trace" aria-hidden="true"></div></div></section>
<section class="cie-section" id="beyond"><div class="cie-inner"><p class="eyebrow">02 — Beyond representation</p><h2>A professional life cannot be reduced to its latest summary.</h2><div class="comparison"><article><h3>Most tools begin with representation</h3><p>Titles, skills, profiles, and documents describe only what has already been made visible.</p></article><article class="cie-side"><h3>CIE begins with capability</h3><p>It helps uncover the capability cultivated through your work and builds a richer understanding of the experience, evidence, contributions, and recurring patterns behind it—including important work that may have disappeared behind a role or title.</p></article></div></div></section>
<section class="cie-section" id="understanding"><div class="cie-inner"><p class="eyebrow">03 — A growing professional understanding</p><h2>Build an understanding grounded in what you have actually done.</h2><div class="understanding"><p>Your experiences, evidence, capability, objectives, contributions, and reflection become connected without being flattened into a score or static profile.</p><ol><li><span>Experience</span> gives the work context.</li><li><span>Evidence</span> grounds what can be understood.</li><li><span>Reflection</span> reveals meaning and uncertainty.</li><li><span>Objectives</span> give the understanding direction.</li></ol></div><div class="capability-diagram" aria-label="Experience, evidence, contribution, reflection, and objectives connect to shape an evolving understanding of capability."><div class="diagram-path" aria-hidden="true"></div><div class="diagram-points"><p><strong>Experience</strong><span>Context</span></p><p><strong>Evidence</strong><span>Grounding</span></p><p><strong>Contribution</strong><span>Change</span></p><p><strong>Reflection</strong><span>Meaning</span></p><p><strong>Objectives</strong><span>Direction</span></p></div><p class="diagram-result">Capability becoming understandable</p></div></div></section>
<section class="cie-section beginnings-section"><div class="cie-inner"><p class="eyebrow">04 — Begin with curiosity</p><h2>Start with what you already have—or simply with what is on your mind.</h2><ol class="beginnings"><li><span>01 — Bring</span><h3>A document or artifact</h3><p>A résumé, review, work sample, project brief, certificate, or something else.</p></li><li><span>02 — Connect</span><h3>Your current representation</h3><p>Begin with how your professional story is represented—and what it may leave out.</p></li><li><span>03 — Talk</span><h3>A conversation</h3><p>Start with a question, experience, objective, uncertainty, or whatever is worth exploring.</p></li></ol></div></section>
<section class="cie-section"><div class="cie-inner"><p class="eyebrow">05 — Capability stays alive</p><h2>Understanding grows through practice, not profile completion.</h2><ol class="craft-flow"><li>Curiosity</li><li>Understanding</li><li>Learning</li><li>Contribution</li><li>Reflection</li></ol><p class="lede">Each return to the cycle can bring new work, evidence, questions, and discoveries into view.</p></div></section>
<section class="cie-section"><div class="cie-inner"><p class="eyebrow">06 — One understanding, many expressions</p><h2>Use what CIE understands without starting from scratch each time.</h2><div class="connected-list"><article><h3>See your landscape</h3><p>Explore connected capability rather than a disconnected list of skills.</p></article><article><h3>Understand opportunities</h3><p>Explore what an opportunity really requires and how that relates to the capability, experience, evidence, and unknowns you bring.</p></article><article><h3>Represent your work</h3><p>Create tailored résumés, cover letters, and other professional representations from an evidence-grounded understanding of your work.</p></article><article><h3>Prepare with context</h3><p>Bring relevant experiences, contributions, evidence, and unknowns into interviews and performance conversations.</p></article></div></div></section>
<section class="cie-section application-section"><div class="cie-inner"><p class="eyebrow">07 — Applications become part of the journey</p><div class="application-memory"><div><h2>Preserve what shaped each pursuit.</h2><p class="lede">Record the opportunity, professional understanding, representations, and discoveries that shaped an application. Reflect on what you learned without treating an interview, offer, or rejection as a verdict on your capability.</p></div><aside class="pursuit-sheet" aria-label="Example application memory"><p class="eyebrow">Application memory</p><dl><div><dt>Opportunity at the time</dt><dd>The context and interpretation you were working from.</dd></div><div><dt>What you brought</dt><dd>The identity, evidence, and representations used.</dd></div><div><dt>What you discovered</dt><dd>New context, questions, and reflections preserved with the journey.</dd></div></dl></aside></div></div></section>
<section class="cie-section"><div class="cie-inner"><p class="eyebrow">08 — Understanding without false certainty</p><h2>CIE keeps what is known separate from what is still emerging.</h2><div class="states"><article><h3>Established</h3><p>Grounded in evidence you can inspect.</p></article><article><h3>Emerging</h3><p>A pattern or interpretation still developing.</p></article><article><h3>Unknown</h3><p>Something worth exploring rather than pretending to know.</p></article></div><p class="lede">Your understanding remains revisable. Outcomes do not become automatic judgments about capability.</p></div></section>
<section class="cie-section trust"><div class="cie-inner trust-grid"><p class="eyebrow">09 — A principle, not a feature</p><div><h2>Your knowledge remains yours.</h2><p>Your information remains private, belongs to you, and can be exported whenever you choose.</p></div></div></section>
<section class="cie-section closing"><div class="cie-inner"><p class="eyebrow">10 — Continue cultivating</p><h2>Your career is bigger than your résumé.</h2><p class="lede">New work, evidence, objectives, applications, and reflection can continue enriching your professional understanding over time.</p><div class="quiet-paths"><a href="#understanding">Revisit how understanding grows</a><a href="../">Return to Alaya Crafts</a></div></div></section>`;

export const ciePage = {
  outputPath: "cie-professional",
  render: (basePath) => renderLayout({ title: "CIE Professional — Alaya Crafts", description: "Build an evidence-grounded understanding of the capability your work has cultivated.", activeRoute: "cie", body, pageClass: "cie-page", pageStyles: "/assets/cie.css", basePath }),
};
