import { renderLayout } from "../shared/layout.mjs";
import { hrefFor } from "../shared/routes.mjs";

const body = (basePath) => `
<section class="section hero"><div class="section-inner"><p class="eyebrow">01 — Curiosity</p><h1>Everything starts with curiosity.</h1><p class="hero-grounding">Capability is the enduring asset within people and organizations.</p><div class="quiet-links"><a href="#idea">Explore the idea</a><a href="./cie-professional/">Meet CIE Professional</a></div><div class="trace" aria-hidden="true"></div></div></section>
<section class="section observation" id="idea"><div class="section-inner"><p class="eyebrow">02 — Observation</p><h2>Much of the value we create is easy to lose and difficult to carry forward.</h2><div class="two-contexts"><article><h3>People</h3><p>Only experience, learning, decisions, evidence, and contribution together can reflect your professional life.</p></article><article><h3>Organizations</h3><p>Knowledge and capability dilute across roles, teams, systems, projects, and moments of change.</p></article></div></div></section>
<section class="section thesis"><div class="section-inner"><p class="eyebrow">03 — Thesis</p><div class="thesis-lines"><p>Capability is the enduring asset.</p><p>Knowledge preserves it.</p><p>Technology extends it.</p></div></div></section>
<section class="section practice"><div class="section-inner"><p class="eyebrow">04 — Practice</p><h2>Capability stays alive through practice.</h2><ol class="practice-sequence"><li>Curiosity</li><li>Understanding</li><li>Learning</li><li>Contribution</li><li>Reflection</li></ol><p class="practice-note">Curiosity opens a question. Each practice enhances capability and opens a new question.</p></div></section>
<section class="section living-field"><div class="section-inner"><p class="eyebrow">05 — The Living Field</p><h2>Capability becomes visible and actionable.</h2><p class="lede">Knowledge, technology, intelligence, and practice help reveal, connect, and cultivate a shared capability landscape.</p><div class="landscape" aria-label="Conceptual capability landscape"><picture><source srcset="${hrefFor("/assets/alaya-05-living-field-mobile.svg", basePath)}" media="(max-width: 820px)"><img class="field-svg" src="${hrefFor("/assets/alaya-05-living-field-desktop.svg", basePath)}" alt="" aria-hidden="true"></picture><p class="field-label capability">Capability <small>The terrain.</small></p><p class="field-label knowledge">Knowledge <small>Definition and memory.</small></p><p class="field-label technology">Technology <small>Connection and use.</small></p><p class="field-label intelligence">Intelligence <small>Relationships becoming visible.</small></p></div></div></section>
<section class="section forms"><div class="section-inner"><p class="eyebrow">06 — Where the idea is taking form</p><div class="cie-definition"><h2>Capability Intelligence Engine <span>(CIE)</span></h2><div><p>A way of making capability understandable through the knowledge, evidence, experiences, and relationships that give it shape. When capability becomes visible, its relationships can become understandable.</p><p>Alaya calls this Capability Intelligence: understanding capability through the knowledge, evidence, experience, objectives, and relationships that surround it.</p><p>The Capability Intelligence Engine (CIE) is the technology Alaya is building to make that understanding usable.</p></div></div><h3 class="scale-title">One landscape. Different scales and ways of understanding it.</h3><div class="maturity"><article class="present"><p>Living expression today</p><h3>CIE Professional</h3><p>A place for a person to begin understanding the capability their work has created.</p></article><div class="future"><article><h3>Teams</h3><p>An emerging direction.</p></article><article><h3>Organizations</h3><p>A broader scale with practical work today.</p></article><article><h3>Collective Intelligence</h3><p>A future possibility: learning from patterns across capability landscapes while preserving the distinction between individual knowledge and collective insight.</p></article></div></div></div></section>
<section class="section cie"><div class="section-inner"><p class="eyebrow">07 — CIE Professional</p><div class="product"><div class="product-glimpse"><p>Your understanding</p><div class="product-mountain"><img class="mountain-scene" src="${hrefFor("/assets/alaya-07-horizon.svg", basePath)}" alt="" aria-hidden="true"></div><blockquote>A recurring theme is beginning to emerge from the work you’ve brought into view.</blockquote></div><div><h2>Understand the capability your work has cultivated.</h2><p class="lede">Build an evidence-grounded understanding of your professional capability, and let it grow with your experience, objectives, reflection, and contribution.</p><a class="text-link" href="./cie-professional/">Explore CIE Professional</a></div></div></div></section>
<section class="section organizations"><div class="section-inner"><p class="eyebrow">08 — Organizations</p><h2>Capability connects strategy to the work that carries it.</h2><p class="lede">Understanding capability changes how people and organizations can think about what comes next: what they can already pursue, what they can draw upon, and what they may need to cultivate.</p><ol class="questions"><li>Where does strategy lose coherence as it becomes work?</li><li>What knowledge disappears between teams or systems?</li><li>What capability already exists but remains fragmented or difficult to reuse?</li></ol></div></section>
<section class="section origin"><div class="section-inner origin-grid"><p class="eyebrow">09 — Origin</p><p>Alaya grew from more than two decades of work across technology, engineering, leadership, product thinking, organizational systems, knowledge, and execution—and the realization that capability was the more enduring thread connecting them.</p></div></section>
<section class="section epilogue"><div class="section-inner"><p class="eyebrow">10 — Epilogue</p><p class="craft-words">Curiosity. <span>Understanding.</span> Learning. <span>Contribution.</span> Reflection.</p><p>These are the crafts.</p><h2>Technology evolves. Crafts endure.</h2></div></section>
<section class="section paths"><div class="section-inner"><p class="eyebrow">11 — Open paths</p><div class="contact-invitation"><p>If something here connects with a question you’re exploring, start a conversation.</p><a href="./contact/">Write to Alaya</a></div><nav class="open-paths" aria-label="Continue exploring"><a href="./cie-professional/">Explore CIE Professional</a><a href="./for-organizations/">For Organizations</a><a href="./ideas/">Follow the Ideas</a></nav></div></section>`;

export const homePage = {
  outputPath: "/",
  render: (basePath) => renderLayout({ title: "Alaya Crafts — Capability is the enduring asset", description: "Alaya Crafts cultivates lasting capability through crafts, knowledge, and technology.", activeRoute: "home", body: body(basePath), pageClass: "home-page", pageStyles: "/assets/home.css", basePath }),
};
