import { renderLayout } from "../shared/layout.mjs";

const ARTICLE_PATH = "./the-rule-we-had-to-keep-re-learning-while-building-cie/";

const body = `
<section class="ideas-section ideas-opening"><div class="ideas-inner"><p class="eyebrow">01 — Ideas</p><h1>An evolving body of thought.</h1><p class="lede">Ideas are another way Alaya explores the capability landscape.</p><p class="quiet">They develop through practice, observation, technology, design, and reflection. Some have reached a developed point of view. Others remain questions worth keeping open.</p></div></section>
<section class="ideas-section ideas-featured"><div class="ideas-inner ideas-featured-grid"><div><p class="eyebrow">02 — Current inquiry</p></div><div><div class="meta-line"><span>Field Work</span><span class="status">Developed</span><span>27 August 2026</span></div><h2 class="feature-title"><a href="${ARTICLE_PATH}">The rule we had to keep re-learning while building CIE</a></h2><p class="excerpt">Building a system meant to hold evidence to a higher standard than assertion required holding the team's own work to the same standard — repeatedly, in places nobody but the team would ever see.</p><a class="read-link" href="${ARTICLE_PATH}">Read the field work</a></div></div></section>
<section class="ideas-section ideas-formats"><div class="ideas-inner ideas-formats-grid"><div><p class="eyebrow">03 — Ways of reading</p><h2>Different forms hold ideas at different stages.</h2><p class="format-note">A format appears only when genuine material exists to inhabit it.</p></div><div class="format-list"><div class="format"><h3>Essays</h3><p>Developed arguments and points of view that benefit from sustained reading.</p></div><div class="format"><h3>Notes</h3><p>Shorter observations, questions, and ideas that may still be taking shape.</p></div><div class="format"><h3>Field Work</h3><p>Practices, methods, and lessons grounded in actual work, where appropriate and publishable.</p></div></div></div></section>
<section class="ideas-section"><div class="ideas-inner"><p class="eyebrow">04 — The body of thought</p><h2>Published so far</h2><div class="index-list"><div class="index-item"><div class="index-date">27 Aug 2026</div><div><h3 class="index-title"><a href="${ARTICLE_PATH}">The rule we had to keep re-learning while building CIE</a></h3><p class="index-excerpt">Building a system meant to hold evidence to a higher standard than assertion required holding the team's own work to the same standard — repeatedly, in places nobody but the team would ever see.</p></div><div class="index-meta"><span>Field Work</span><span class="status">Developed</span></div></div></div></div></section>
<section class="ideas-section ideas-other-voices"><div class="ideas-inner ideas-other-voices-grid"><div><p class="eyebrow">05 — Other Voices</p><h2>Ideas from beyond the studio</h2></div><div class="other-voices-copy"><p>Alaya's own thinking sits above. This is space for people working through similar questions from the outside — in their own name, in their own voice.</p><p class="empty-status">Nothing has been published here yet. If you're working through something that belongs in this kind of space, reach out.</p><a class="read-link" href="../contact/">Share something you've written</a></div></div></section>
<section class="ideas-section ideas-open-end"><div class="ideas-inner"><p class="eyebrow">06 — Open end</p><h2>Keep following the questions.</h2><a class="read-link" href="./">Follow the Ideas</a></div></section>`;

export const ideasPage = {
  outputPath: "ideas",
  render: (basePath) => renderLayout({ title: "Ideas — Alaya Crafts", description: "An evolving body of thought from Alaya Crafts, explored through essays, notes, and field work.", activeRoute: "ideas", body, pageClass: "ideas-page", pageStyles: "/assets/ideas.css", basePath }),
};
