import { renderLayout } from "../shared/layout.mjs";

const body = `
<section class="org-section org-hero"><div class="org-inner"><p class="eyebrow">01 — For Organizations</p><h1>What CIE Professional begins with one person, Alaya is learning to understand at organizational scale.</h1><div class="lineage"><p>CIE Professional builds an evidence-grounded understanding of capability from the work, experience, evidence, reflection, objectives, and relationships that give it shape.</p><p>The same principle matters across an organization: capability should be understood through the work that reveals it, not assumed from roles, structures, or headcount.</p></div><p class="status-note">CIE Organization is a direction under development—not yet a launched product.</p></div></section>
<section class="org-section thesis"><div class="org-inner"><p class="eyebrow">02 — Thesis</p><div class="thesis-lines"><p>Strategy gives capability direction.</p><p>Capability turns strategy into action.</p></div><p class="lede">Strategy can set a clear destination while leaving a harder question unanswered: does the capability to carry it out already exist, is it fragmented, or was it never there?</p></div></section>
<section class="org-section"><div class="org-inner"><p class="eyebrow">03 — The organizational condition</p><h2>A network operations team needed to pivot and upskill to support a CDN solution. Leadership opted for training from the provider.</h2><div class="case-field"><p>That decision looked aligned. It began from an incomplete picture.</p><p>But the decision itself was built on a miscalibration—overstating what some engineers already knew, and underestimating what others were capable of.<br><br>Without visibility into actual capability, resources drain, motivation erodes, and strategy stalls.</p></div></div></section>
<section class="org-section"><div class="org-inner"><p class="eyebrow">04 — What is difficult to see</p><h2>Organizations can misread capability in both directions at once.</h2><div class="decision-line"><article><h3>Overstated</h3><p>A role, reputation, or past exposure implies depth the work does not yet support.</p></article><p class="same-decision">One decision.<br>Two misreadings.</p><article><h3>Underestimated</h3><p>Valuable capability remains hidden behind assignment, title, visibility, or circumstance.</p></article></div><p class="visibility-explanation">Both readings can grow from the same conditions: knowledge fragmented across teams and systems, important capability remaining implicit in practice, and what already exists unable to travel to the work that needs it.</p></div></section>
<section class="org-section lens"><div class="org-inner lens-grid"><div><p class="eyebrow">05 — A different lens</p><h2>What changes when capability becomes a unit of understanding?</h2><p class="lens-shift">The value of a strategy can only be revealed by the capability to execute it.</p></div><figure class="landscape"><div class="onion-field" aria-label="A four-ring capability landscape: Value outside Knowledge, Knowledge outside Teams, and People at the core."><div class="onion-ring value"></div><div class="onion-ring knowledge"></div><div class="onion-ring teams"></div><div class="onion-ring people"></div><span class="onion-label value">Value</span><span class="onion-label knowledge">Knowledge</span><span class="onion-label teams">Teams</span><span class="onion-label people">People</span></div><figcaption>Capability landscape</figcaption></figure></div></section>
<section class="org-section"><div class="org-inner"><p class="eyebrow">06 — Questions Alaya explores</p><h2>The direction begins with questions, not a service catalogue.</h2><ol class="questions"><li>Where does strategy depend on capability the organization cannot yet see clearly?</li><li>What knowledge disappears between teams, systems, or changes in responsibility?</li><li>Where is technology introduced without the capability needed to sustain it?</li><li>What capability already exists but remains fragmented, implicit, or difficult to reuse?</li><li>Which training decisions begin before the real starting point is understood?</li></ol></div></section>
<section class="org-section technology"><div class="org-inner technology-grid"><div><p class="eyebrow">07 — Technology’s role</p><h2>Technology can connect understanding.</h2></div><p><strong>It cannot substitute for capability.</strong><br><br>Its role is to help preserve evidence, reveal relationships, connect knowledge to work, and make an evolving capability landscape usable. The people, work, and knowledge remain the source.</p></div></section>
<section class="org-section provenance"><div class="org-inner"><p class="eyebrow">08 — Human provenance</p><p>This direction grew from more than two decades of work across technology, engineering, network operations, leadership, product thinking, organizational systems, knowledge, and execution—and from repeatedly seeing how much important capability remains difficult to recognize until the work demands it.</p></div></section>
<section class="org-section paths"><div class="org-inner"><p class="eyebrow">09 — Open paths</p><div class="open-paths"><article><h3>Help shape the direction</h3><p>If this matches something you have seen, and you would want to help shape CIE Organization before launch, share the experience with Alaya.</p><a href="mailto:curious@alayacrafts.com">Share what you have seen</a></article><article><h3>Start a general conversation</h3><p>If something here connects with a question you are exploring, an idea you are developing, or work you are trying to understand, write to Alaya directly. Your message will be read and answered by a person.</p><a href="../contact/">Contact Alaya</a></article></div></div></section>`;

export const organizationsPage={outputPath:"for-organizations",render:(basePath)=>renderLayout({title:"For Organizations — Alaya Crafts",description:"Explore capability as the connection between organizational strategy and the work that carries it.",activeRoute:"organizations",body,pageClass:"organizations-page",pageStyles:"/assets/organizations.css",basePath})};
